[package]
name = "rlocation"
version = "0.1.0"
edition = "2024"

[dependencies]
embed_plist = "1.2.2"
libui = "0.4.0"
public-ip-address = {git="https://github.com/ghztomash/public-ip-address", features = ["blocking"]}
